@echo off
if exist %~dp0venv\ (
    echo venv path already exists, ignoring...
) else (
    echo venv path does not exist, creating...
    python -m venv venv
)
echo enabling venv...
call %~dp0venv\Scripts\activate
echo updating pip and requirements...
python -m pip install --upgrade pip
pip install --upgrade setuptools wheel
pip install --upgrade -r %~dp0requirements.txt
echo checking project...
python %~dp0manage.py check
echo making migrations...
python %~dp0manage.py makemigrations
echo migrating...
python %~dp0manage.py migrate
echo collecting static...
python %~dp0manage.py collectstatic --no-input
echo starting server in 'localhost:8000'...
python %~dp0manage.py runserver localhost:8000
